### ISSUE TITLE
in Autocomplete() is filter for count < model.Maxcount/50 wrong or arbitrary?

### ISSUE THREAD

**Issue by mschoch** [sajari/fuzzy#10] opened 2015-04-10 15:20 UTC
See line: https://github.com/sajari/fuzzy/blob/master/fuzzy.go#L507

When testing use of autocomplete on a small dataset I found that this restriction was problematic, as model.Maxcount/50 is always 0.  I don't understand the purpose of this rule as it would seem to exclude the most popular matches.  And if there is some reason for I'm not getting, isn't 50 just going to be arbitrary, should it be configurable?

**Comment by mish15** [comment] 2015-04-10 22:31
It probably should be dynamic, tunable, or a combo. The issue is with
decent size data sets, the most popular suggestions are common junk. The 50
basically says if a term is in over 2% of corpus docs it is too common to
be suggested.

If you train with user queries this is a problem, if you train with a
corpus this works fine.

So the options are:
a) make this configurable
b) make the package support different modes of use
c) add a parameter to the suggest func or add different suggest functions
d) adapt the training to count queries and corpus term occurrences and use
them accordingly

**Comment by mschoch** [comment] 2015-04-12 12:25
Thanks for the clarification.  I haven't worked with training an auto suggester from user queries before, can you give an example  of user types "..." and suggestion is "..." but we consider this suggestion "junk"?  I'd just like to better understand the problem.

I would vote for either making it configurable or a parameter.  Also, it might make sense to split out the autocomplete matching logic from the returning top N results (the same way the Potentials() method does).

**Comment by mish15** [comment] 2015-04-13 01:26
Cool, no worries. Documents contain a very different term distribution to user queries, so *most popular* is typically not useful for autocomplete if you train with docs. 

If you train with real user queries, the autocomplete can happily suggest the most popular terms though, as you are suggesting the most likely queries. If you train with documents or a corpus, then the most popular terms no longer correlate with the most popular queries. An example where popular is a problem if trained by a corpus:
- user types "ev" and the most popular suggestion is "every", but we think it should be "everest".

I think the problem here is designing for multiple objectives. Autocomplete should probably be trained by queries, spell check should probably be trained by documents. I think it might be worth adding in a second count accordingly.

**Comment by mish15** [comment] 2015-04-13 06:17
I think maybe the solution is to:
- [ ] Change Model.Data into a `map[string][2]int` and keep counts for normal training [0] and queries [1]
- [ ] Add a new query trainer to increment the term count, e.g. 
```go
func (model *Model) TrainQuery(term string) {
```
- [ ] Add a max query count (highest number of queries on a single term)
- [ ] Change the `Autocomplete` function to sort on Query count first, then normal term count.

Thoughts?

**Comment by mish15** [comment] 2015-05-19 02:34
@mschoch just checking back in on this. Thoughts?

**Comment by mschoch** [comment] 2015-05-19 03:04
I don't have a whole lot of input.  Your proposal seems reasonable.  I tend to agree that there are multiple use cases going on here.  What I wonder is if the API should accommodate multiple use cases at the same time?  Or is it better to have users create separate models for each use case, and just use them accordingly.  Some of the use cases we're looking at supporting are working as a library, where we most likely won't have query logs available for training.  Are suggestions trained from the document corpus a lot worse?  Maybe, but sometimes thats still better than nothing.  I'm wandering here, but I'm probably arguing for maximum flexibility.

**Comment by mish15** [comment] 2015-05-19 04:12
#### Re: multiple use cases
No worries, but yes i think you've answered your own question! :) Supporting both at the same time is kind of required, as it allows the suggestions to gracefully fall back on any other training (possibly for spelling etc) when no matching queries are trained. 

#### Re: corpus suggestions
The query suggestions from a general corpus of documents aren't great, people don't search for super popular terms (close to stop words) or super rare terms (spelling mistakes), so the ideal responses tend to be in the middle, hence the "hack" number of 50 you found problematic.

ok i'll look at getting this in and tested and see how it performs. We have ~250k queries rattling through daily, so it should be quick to get some training data.

**Comment by mish15** [comment] 2015-06-15 10:01
@mschoch see https://github.com/sajari/fuzzy/pull/11 and let me know what you think. This adds a new function `model.TrainQuery(term)` that allows you to specifically train with queries as opposed to corpus text. The sorting of autocomplete results now uses the query count as the first sort measure, so autocomplete should follow query popularity where possible and fall back on terms elsewhere.

**Comment by mish15** [comment] 2015-08-03 06:50
Closing. Changes merged. @mschoch be sure to use the new Query training endpoint for autocomplete.

**Closed by mish15** 2015-08-03 06:50 UTC
Labels: enhancement
